language: node_js
node_js:
  - 0.12
env:
  global:
    - GH_REF: github.com/vaeum/template.git
    - secure: pvofoFoksxY3y58UOhMsg/Ge12b10pL+7L0Or5ckFDpdi5etzpYE658ZMPtXv3HzyJqOpzzJ+uqewXEPhFI5eLznlynwNYNopHaX4jF8mAXt29UUdbQiabSxZ2CcwmbVWAjTQdeeZDdMXzu9xyRrxUZCX0EKYbTDhATfGWI6AE5k7nZviPi0odvV15BMxIzlE52xU78ym3WGbwjTm2A9VIUOdMxZUX2j/mLOTDfLdbNvf10A9JB6CSmqCc5OL49lsM0vgIcQa9g5AgGp8tLYbvxoIcyrctzN4gFo7qWClsnJEdFJhw9oWY+VneWqLhU6KHd/4oGD9WsD9jwz7ffohKsoioH/czbMaMUsHY6l/Bd+a95bwe/OM5QTXFddOjD+/HogbzdNET8cU7aHObsZUtgVi35gRIR0EVg87GCZh6OsWND/o3qrYdbcMuusEbXt+lkWowUJ+54r4VCXg3ux/95qeKrl42drgw8yrpzq/40Nyzm+fHY0md5bhpecFh/fgIrCgXrsMjBSppaPux7TsCWFjMoxy2EBSWwDeqv+xXBDoUxgCXqq+Ufuo/d0BpRGRJZmanUBEM7vvTp26MA8n8BrelWWk2+/ufrBD4lnd6CIr6FyJKJVuVf+hDqmrFNfacjy20qZpd85KmF+OgsqRJvcveXOjY/PFSAMLWMZdC4=
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm run build
script:
  - cd app
  - git init
  - 'git config user.name "Alexander Anpleenko"'
  - 'git config user.email "vaeum@yahoo.com"'
  - git add .
  - 'git commit -m "Deploy to GitHub Pages"'
  - 'git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1'
